# Generated by Django 5.2 on 2025-04-10 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 10, 7, 32, 0, 412100, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de Publicación",
            ),
        ),
    ]
