# Generated by Django 5.2 on 2025-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="get_posts",
                to="blog.category",
                verbose_name="Categorías",
            ),
        ),
    ]
