# Generated by Django 5.2 on 2025-04-10 12:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenido"),
        ),
    ]
